# Generated by Django 3.1.2 on 2021-11-09 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allcourses', '0004_auto_20211108_2221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course_details',
            old_name='lecture_title',
            new_name='title',
        ),
        migrations.AddField(
            model_name='course_details',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True, unique=True),
        ),
    ]
