# Generated by Django 3.1.2 on 2021-11-14 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allcourses', '0005_auto_20211109_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_details',
            name='lecture_body1',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='course_details',
            name='lecture_imgae1',
            field=models.ImageField(blank=True, null=True, upload_to='all_courses'),
        ),
        migrations.AddField(
            model_name='course_details',
            name='lecture_title1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
