# Generated by Django 3.1.2 on 2022-01-20 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allcourses', '0007_auto_20211122_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_details',
            name='video_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
