# Generated by Django 3.1.2 on 2022-01-20 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allcourses', '0008_course_details_video_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_details',
            name='video_link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
