# Generated by Django 3.1.2 on 2022-03-10 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allcourses', '0009_auto_20220120_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_details',
            name='link_height',
            field=models.IntegerField(blank=True, default=True),
            preserve_default=False,
        ),
    ]
