# Generated by Django 3.1.2 on 2022-03-10 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allcourses', '0011_course_details_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_details',
            name='video',
            field=models.FileField(blank=True, upload_to='video'),
        ),
    ]
