# Generated by Django 3.1.2 on 2022-03-10 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allcourses', '0012_auto_20220310_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_details',
            name='video_height',
            field=models.IntegerField(blank=True, default=True),
            preserve_default=False,
        ),
    ]
