# Generated by Django 3.1.2 on 2022-03-11 07:05

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allcourses', '0014_auto_20220310_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_details',
            name='lecture_body',
            field=ckeditor.fields.RichTextField(blank=True, default=True),
            preserve_default=False,
        ),
    ]
