# Generated by Django 3.1.4 on 2022-06-13 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allcourses', '0015_auto_20220311_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_details',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='video'),
        ),
    ]
