# Generated by Django 3.1.4 on 2022-06-13 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allcourses', '0016_auto_20220613_2133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course_details',
            name='lecture_imgae',
        ),
        migrations.AddField(
            model_name='course_details',
            name='lecture_image',
            field=models.ImageField(blank=True, null=True, upload_to='all_courses'),
        ),
    ]
