# Generated by Django 3.2.6 on 2021-09-24 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0025_alter_user_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='unit',
        ),
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True, unique=True),
        ),
    ]
