# Generated by Django 3.1.2 on 2022-01-20 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0027_auto_20211108_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='skill',
            field=models.TextField(default=True, max_length=20000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lecture',
            name='skill2',
            field=models.CharField(default=True, max_length=20000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lecture',
            name='skill3',
            field=models.CharField(default=True, max_length=20000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lecture',
            name='skill4',
            field=models.CharField(default=True, max_length=20000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lecture',
            name='skill5',
            field=models.CharField(default=True, max_length=20000),
            preserve_default=False,
        ),
    ]
