# Generated by Django 3.1.2 on 2022-01-20 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0028_auto_20220120_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='skill',
            field=models.CharField(max_length=20000),
        ),
    ]
