# Generated by Django 3.1.2 on 2022-01-20 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0030_auto_20220120_1136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='skill',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='skill2',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='skill3',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='skill4',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='skill5',
        ),
        migrations.AddField(
            model_name='course',
            name='skill',
            field=models.CharField(default=True, max_length=20000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='skill2',
            field=models.CharField(default=True, max_length=20000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='skill3',
            field=models.CharField(default=True, max_length=20000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='skill4',
            field=models.CharField(default=True, max_length=20000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='skill5',
            field=models.CharField(default=True, max_length=20000),
            preserve_default=False,
        ),
    ]
