# Generated by Django 3.1.2 on 2022-01-20 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0031_auto_20220120_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='skill',
            field=models.CharField(blank=True, max_length=20000),
        ),
        migrations.AlterField(
            model_name='course',
            name='skill2',
            field=models.CharField(blank=True, max_length=20000),
        ),
        migrations.AlterField(
            model_name='course',
            name='skill3',
            field=models.CharField(blank=True, max_length=20000),
        ),
        migrations.AlterField(
            model_name='course',
            name='skill4',
            field=models.CharField(blank=True, max_length=20000),
        ),
        migrations.AlterField(
            model_name='course',
            name='skill5',
            field=models.CharField(blank=True, max_length=20000),
        ),
    ]
