# Generated by Django 3.1.2 on 2022-02-27 13:52

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0032_auto_20220120_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='discription',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
