# Generated by Django 3.1.2 on 2022-03-11 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0033_auto_20220227_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='lecturer',
            field=models.CharField(default=True, max_length=1000),
            preserve_default=False,
        ),
    ]
