# Generated by Django 3.1.2 on 2022-04-04 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0035_course_lecturer_social_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='intro_video',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
